# Generated by Django 4.0.2 on 2022-06-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_system', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='outro',
        ),
    ]
